server:
  port: 8088
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.91.56.32:3307/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: rootROOT12...@@@
  redis:
    host: 122.91.56.32
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS